<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
 */

	'defaults' => [
		'guard' => 'web',
		'passwords' => 'users',
	],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
	 */

	'guards' => [
		'web' => [
			'driver' => 'session',
			'provider' => 'users',
		],

		'api' => [
			'driver' => 'jwt',
			'provider' => 'users',
		],
	],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
	 */

	'providers' => [
		'users' => [
			'driver' => 'eloquent',
			'model' => App\User::class,
		],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
	],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
	 */

	'passwords' => [
		'users' => [
			'provider' => 'users',
			'table' => 'password_resets',
			'expire' => 60,
		],
	],

    'url_local' => 'http://bravokoperasi.test/',
    'url_server' => 'http://115.124.64.250:84/',

	'level' => [
		'POWERADMIN' => ["name"=>"POWERADMIN","friendly_name"=> "Power Admin"],
		'SUPERADMIN' => ["name"=>"SUPERADMIN","friendly_name"=> "Super Admin"],
		'PENGAWAS1' => ["name"=>"PENGAWAS_1","friendly_name"=> "Pengawas 1"],
		'PENGAWAS2' => ["name"=>"PENGAWAS_2","friendly_name"=> "Pengawas 2"],
		'PENGAWAS3' => ["name"=>"PENGAWAS_3", "friendly_name"=> "Pengawas 3"],
		'PENGURUS1' => ["name"=>"PENGURUS_1","friendly_name"=> "Pengurus 1"],
		'PENGURUS2' => ["name"=>"PENGURUS_2","friendly_name"=> "Pengurus 2"],
		'SUPERVISOR' => ["name"=>"SUPERVISOR","friendly_name"=> "Supervisor"],
		'ADMINKOPERASI' => ["name"=>"ADMIN_KOPERASI","friendly_name"=> "Admin Koperasi"],
		'GENERALMANAGER' => ["name"=>"GENERAL_MANAGER", "friendly_name"=> "General Manager"],
		'MANAGER' => ["name"=>"MANAGER","friendly_name"=> "Manager"],
		'ADMINAREA' => ["name"=>"ADMIN_AREA", "friendly_name"=> "Admin Area"],
		'DANSEK' => ["name"=>"DANSEK", "friendly_name"=> "Dansek"],
        'ANGGOTA'=> ["name"=>"MEMBER", "friendly_name"=>"Anggota"],
        'DIREKTURUTAMA'=> ["name"=>"DIREKTUR_UTAMA", "friendly_name"=>"Direktur Utama"],
        'DIREKTUR'=> ["name"=>"DIREKTUR", "friendly_name"=>"Direktur"],
        'PENDIRI'=> ["name"=>"PENDIRI", "friendly_name"=>"Pendiri"],
        'KARYAWANPENGELOLA'=> ["name"=>"KARYAWAN_PENGELOLA", "friendly_name"=>"Karyawan Pengelola"],
        'KARYAWANKOPERASI'=> ["name"=>"KARYAWAN_KOPERASI", "friendly_name"=>"Karyawan Koperasi"],
        'PENGELOLAAREA'=> ["name"=>"PENGELOLA_AREA", "friendly_name"=>"Pengelola Area"],
        'KOMISARIS'=> ["name"=>"KOMISARIS", "friendly_name"=>"Komisaris"],
        'HRD'=> ["name"=>"HRD", "friendly_name"=>"Hrd"]
    ],
    'positions'=>  [
        [
        'name'        => 'power',
        'description' => 'power',
        'level_id'    => '1',
        'order_level' => '0',
        'created_at'  => new DateTime,
        'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'superadmin',
            'description' => 'superadmin',
            'level_id'    => '2',
            'order_level' => '1',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
		[
			'name'        => 'pengawas_satu',
			'description' => 'pengawas 1',
			'level_id'    => '3',
			'order_level' => '2',
			'created_at'  => new DateTime,
			'updated_at'  => new DateTime,
		],
		[
			'name'        => 'pengawas_dua',
			'description' => 'pengawas 2',
			'level_id'    => '4',
			'order_level' => '3',
			'created_at'  => new DateTime,
			'updated_at'  => new DateTime,
		],
		[
			'name'        => 'pengawas_tiga',
			'description' => 'pengawas 3',
			'level_id'    => '5',
			'order_level' => '4',
			'created_at'  => new DateTime,
			'updated_at'  => new DateTime,
		],
        [
            'name'        => 'pengurus_satu',
            'description' => 'pengurus 1',
            'level_id'    => '6',
            'order_level' => '5',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'pengurus_dua',
            'description' => 'pengurus 2',
            'level_id'    => '7',
            'order_level' => '6',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
		[
			'name'        => 'supervisor',
			'description' => 'supervisor',
			'level_id'    => '8',
			'order_level' => '7',
			'created_at'  => new DateTime,
			'updated_at'  => new DateTime,
		],
        [
            'name'        => 'admin_koperasi',
            'description' => 'admin koperasi',
            'level_id'    => '9',
            'order_level' => '8',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
		[
			'name'        => 'general_manager',
			'description' => 'general manager',
			'level_id'    => '10',
			'order_level' => '9',
			'created_at'  => new DateTime,
			'updated_at'  => new DateTime,
		],
		[
			'name'        => 'manager',
			'description' => 'manager',
			'level_id'    => '11',
			'order_level' => '10',
			'created_at'  => new DateTime,
			'updated_at'  => new DateTime,
		],
        [
            'name'        => 'admin_area',
            'description' => 'admin area',
            'level_id'    => '12',
            'order_level' => '11',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'dansek',
            'description' => 'dansek',
            'level_id'    => '13',
            'order_level' => '12',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'anggota',
            'description' => 'anggota security',
            'level_id'    => '14',
            'order_level' => '13',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'direktur_utama',
            'description' => 'direktur utama',
            'level_id'    => '15',
            'order_level' => '14',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'direktur',
            'description' => 'direktur',
            'level_id'    => '16',
            'order_level' => '15',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'pendiri',
            'description' => 'pendiri',
            'level_id'    => '17',
            'order_level' => '16',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'karyawan_pengelola',
            'description' => 'karyawan pengelola',
            'level_id'    => '18',
            'order_level' => '17',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'karyawan_koperasi',
            'description' => 'karyawan koperasi',
            'level_id'    => '19',
            'order_level' => '20',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'pengelola_area',
            'description' => 'pengelola area',
            'level_id'    => '20',
            'order_level' => '19',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'komisaris',
            'description' => 'komisaris',
            'level_id'    => '21',
            'order_level' => '20',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ],
        [
            'name'        => 'hrd',
            'description' => 'hrd',
            'level_id'    => '22',
            'order_level' => '21',
            'created_at'  => new DateTime,
            'updated_at'  => new DateTime,
        ]],

    "permissions"=> [
        "account.register",
        "account.login",
        "account.forgot_password",
        "account.bank_data",

        "dashboard.loan_total",
        "dashboard.deposit_total",
        "dashboard.member_card",
        "dashboard.news",

        "deposit.main_deposit",
        "deposit.required_deposit",
        "deposit.voluntary_deposit",
        "deposit.shu",
        "deposit_transaction.deposit_application",
        "deposit_transaction.cashing_application",
        "deposit_transaction.cashing",
        "deposit_transaction.history",

        "loan.application",
        "loan.approval",
        "loan.detail",
        "loan.history",
        "loan.transaction",

        "shu.config",
        "shu.history",

        "member",
        "member.total_member",
        "member.configuration",
        "member.registration",
        "member.work_configuration",
        "member.bank",
        "member.resign",
        "member.profile",
        "member.loan",
        "member.deposit",
        "member.staffinfo",
        "member.plafond",
        "member.qna",

        "approve.deposit",
        "approve.loan",

        "generate.report.deposit",
        "generate.report.loan",
        "generate.report.member",

        "report",
        "report.deposit",
        "report.loan",
        "report.member",
        "report.npl",

        "auth.level",
        "auth.permission",
		"auth.user",

		"auth.management",
		"project.management",
		"transaction.management",

        "master.area",
        "master.branch",
        "master.transaction-type",
        "master.location",
        "master.project",
        "master.position",
        "master.setting",
        "master.policy",

        "report.per_member",
        "report.per_area",
        "report.annual_loan",
        "report.annual_deposit",
        "report.annual_shu",
        "master.shu",
        "master.deposit",
        "master.loan",

        "transaction.member.plafond",
        "transaction.member.loan",
        "transaction.member.deposit",
        "transaction.member.retrieve.deposit",
        "transaction.member.change.deposit",

        "transaction.deposit",
        "management.import",
        "account.configuration"
    ],
    "privileges"=> [
        "SUPERADMIN" => [
                "view.transaction.management",
                "view.account.register",
                "create.account.register",
                "update.account.register",
                "delete.account.register",
                "view.account.login",
                "create.account.login",
                "update.account.login",
                "delete.account.login",
                "view.account.forgot_password",
                "create.account.forgot_password",
                "update.account.forgot_password",
                "delete.account.forgot_password",
                "view.account.bank_data",
                "create.account.bank_data",
                "update.account.bank_data",
                "delete.account.bank_data",
                "view.dashboard.loan_total",
                "update.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "update.dashboard.deposit_total",
                "view.dashboard.member_card",
                "update.dashboard.member_card",
                "view.dashboard.news",
                "update.dashboard.news",
                "view.deposit.main_deposit",
                "update.deposit.main_deposit",
                "view.deposit.required_deposit",
                "update.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "update.deposit.voluntary_deposit",
                "view.deposit.shu",
                "update.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.approval",
                "update.loan.approval",
                "view.loan.detail",
                "update.loan.detail",
                "view.shu.config",
                "update.shu.config",
                "view.shu.history",
                "update.shu.history",
                "view.report.per_member",
                "create.report.per_member",
                "update.report.per_member",
                "view.report.per_area",
                "create.report.per_area",
                "update.report.per_area",
                "view.report.annual_loan",
                "create.report.annual_loan",
                "update.report.annual_loan",
                "view.report.annual_deposit",
                "create.report.annual_deposit",
                "update.report.annual_deposit",
                "view.report.annual_shu",
                "create.report.annual_shu",
                "update.report.annual_shu",
                "view.loan.transaction",
                "view.auth.management",
                "view.auth.user",
                "create.auth.user",
                "update.auth.user",
                "delete.auth.user",
                "view.member.profile",
                "create.member.profile",
                "update.member.profile",
                "delete.member.profile",
                "view.approve.deposit",
                "create.approve.deposit",
                "update.approve.deposit",
                "delete.approve.deposit",
                "view.approve.loan",
                "create.approve.loan",
                "update.approve.loan",
                "delete.approve.loan",
                "view.member.loan",
                "create.member.loan",
                "update.member.loan",
                "delete.member.loan",
                "view.member.deposit",
                "create.member.deposit",
                "update.member.deposit",
                "delete.member.deposit",
                "view.member.profile",
                "create.member.profile",
                "update.member.profile",
                "delete.member.profile",
                "view.report",
                "create.report",
                "update.report",
                "delete.report",
                "view.report.deposit",
                "create.report.deposit",
                "update.report.deposit",
                "delete.report.deposit",
                "view.report.loan",
                "create.report.loan",
                "update.report.loan",
                "delete.report.loan",
                "view.project.management",
                "create.project.management",
                "update.project.management",
                "delete.project.management",
                "view.member",
                "create.member",
                "update.member",
                "delete.member",
                "view.member.staffinfo",
                "create.member.staffinfo",
                "update.member.staffinfo",
                "delete.member.staffinfo",
                "view.master.project",
                "create.master.project",
                "update.master.project",
                "delete.master.project",
                "view.master.area",
                "create.master.area",
                "update.master.area",
                "delete.master.area",
                "view.master.branch",
                "create.master.branch",
                "update.master.branch",
                "delete.master.branch",
                "view.master.location",
                "create.master.location",
                "update.master.location",
                "delete.master.location",
                "view.master.position",
                "create.master.position",
                "update.master.position",
                "delete.master.position",
                "view.master.policy",
                "create.master.policy",
                "update.master.policy",
                "delete.master.policy",
                "view.management.import",
                "create.management.import",
                "update.management.import",
                "delete.management.import",
                "view.member.resign",
                "create.member.resign",
                "update.member.resign",
                "delete.member.resign",
                "view.member.plafond",
                "create.member.plafond",
                "update.member.plafond",
                "delete.member.plafond",
                "view.auth.level",
                "create.auth.level",
                "update.auth.level",
                "delete.auth.level",
                "view.master.deposit",
                "create.master.deposit",
                "update.master.deposit",
                "delete.master.deposit",
                "view.master.loan",
                "create.master.loan",
                "update.master.loan",
                "delete.master.loan",
                "view.transaction.member.plafond",
                "create.transaction.member.plafond",
                "update.transaction.member.plafond",
                "delete.transaction.member.plafond",
                "view.transaction.member.loan",
                "create.transaction.member.loan",
                "update.transaction.member.loan",
                "delete.transaction.member.loan",
                "view.transaction.member.deposit",
                "create.transaction.member.deposit",
                "update.transaction.member.deposit",
                "delete.transaction.member.deposit",
                "view.transaction.member.retrieve.deposit",
                "create.transaction.member.retrieve.deposit",
                "update.transaction.member.retrieve.deposit",
                "delete.transaction.member.retrieve.deposit",
                "view.transaction.member.change.deposit",
                "create.transaction.member.change.deposit",
                "update.transaction.member.change.deposit",
                "delete.transaction.member.change.deposit",
                "view.generate.report.deposit",
                "create.generate.report.deposit",
                "update.generate.report.deposit",
                "delete.generate.report.deposit",
                "view.generate.report.loan",
                "create.generate.report.loan",
                "update.generate.report.loan",
                "delete.generate.report.loan",
                "view.generate.report.member",
                "create.generate.report.member",
                "update.generate.report.member",
                "delete.generate.report.member",
                "view.account.configuration",
                "create.account.configuration",
                "update.account.configuration",
                "delete.account.configuration",
                "view.master.qna",
                "create.master.qna",
                "update.master.qna",
                "delete.master.qna"],
        "ADMIN_KOPERASI" => [
                "view.transaction.management",
                "view.account.register",
                "view.account.login",
                "view.account.forgot_password",
                "view.account.bank_data",
                "view.dashboard.loan_total",
                "create.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "create.dashboard.deposit_total",
                "view.dashboard.member_card",
                "create.dashboard.member_card",
                "view.dashboard.news",
                "create.dashboard.news",
                "view.deposit.main_deposit",
                "update.deposit.main_deposit",
                "view.deposit.required_deposit",
                "update.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "update.deposit.voluntary_deposit",
                "view.deposit.shu",
                "update.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "create.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "create.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "create.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "create.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.application",
                "create.loan.application",
                "update.loan.application",
                "view.loan.approval",
                "create.loan.approval",
                "update.loan.approval",
                "view.loan.detail",
                "create.loan.detail",
                "update.loan.detail",
                "view.loan.history",
                "create.loan.history",
                "update.loan.history",
                "view.shu.config",
                "create.shu.config",
                "update.shu.config",
                "delete.shu.config",
                "view.shu.history",
                "create.shu.history",
                "update.shu.history",
                "delete.shu.history",
                "view.member.total_member",
                "view.member.configuration",
                "create.member.configuration",
                "update.member.configuration",
                "view.member.registration",
                "create.member.registration",
                "update.member.registration",
                "delete.member.registration",
                "view.member.bank",
                "create.member.bank",
                "update.member.bank",
                "view.member.resign",
                "create.member.resign",
                "update.member.resign",
                "view.master.area",
                "create.master.area",
                "update.master.area",
                "delete.master.area",
                "view.master.transaction-type",
                "create.master.transaction-type",
                "update.master.transaction-type",
                "delete.master.transaction-type",
                "view.master.location",
                "create.master.location",
                "update.master.location",
                "delete.master.location",
                "view.master.project",
                "create.master.project",
                "update.master.project",
                "delete.master.project",
                "view.master.position",
                "create.master.position",
                "update.master.position",
                "delete.master.position",
                "view.report.per_member",
                "view.report.per_area",
                "view.report.annual_shu",
                "create.report.annual_shu",
                "update.report.annual_shu",
                "delete.report.annual_shu",
                "view.loan.transaction",
                "view.auth.user",
                "create.auth.user",
                "update.auth.user",
                "delete.auth.user",
                "view.project.management",
                "view.master.branch",
                "create.master.branch",
                "update.master.branch",
                "delete.master.branch",
                "view.master.policy",
                "create.master.policy",
                "update.master.policy",
                "delete.master.policy",
                "view.member.plafond",
                "create.member.plafond",
                "update.member.plafond",
                "delete.member.plafond",
                "view.auth.level",
                "create.auth.level",
                "update.auth.level",
                "delete.auth.level",
                "view.master.deposit",
                "create.master.deposit",
                "update.master.deposit",
                "delete.master.deposit",
                "view.master.loan",
                "create.master.loan",
                "update.master.loan",
                "delete.master.loan",
                "view.transaction.member.plafond",
                "create.transaction.member.plafond",
                "update.transaction.member.plafond",
                "delete.transaction.member.plafond",
                "view.transaction.member.loan",
                "create.transaction.member.loan",
                "update.transaction.member.loan",
                "delete.transaction.member.loan",
                "view.transaction.member.deposit",
                "create.transaction.member.deposit",
                "update.transaction.member.deposit",
                "delete.transaction.member.deposit",
                "view.transaction.member.retrieve.deposit",
                "create.transaction.member.retrieve.deposit",
                "update.transaction.member.retrieve.deposit",
                "delete.transaction.member.retrieve.deposit",
                "view.transaction.member.change.deposit",
                "create.transaction.member.change.deposit",
                "update.transaction.member.change.deposit",
                "delete.transaction.member.change.deposit",
                "view.generate.report.deposit",
                "create.generate.report.deposit",
                "update.generate.report.deposit",
                "delete.generate.report.deposit",
                "view.generate.report.loan",
                "create.generate.report.loan",
                "update.generate.report.loan",
                "delete.generate.report.loan",
                "view.generate.report.member",
                "create.generate.report.member",
                "update.generate.report.member",
                "delete.generate.report.member",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "MEMBER" => [
                "view.account.register",
                "create.account.register",
                "view.account.login",
                "create.account.login",
                "view.account.forgot_password",
                "create.account.forgot_password",
                "create.account.bank_data",
                "view.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "view.dashboard.member_card",
                "view.dashboard.news",
                "view.deposit.main_deposit",
                "view.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "view.deposit.shu",
                "create.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "create.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "view.loan.application",
                "create.loan.application",
                "update.loan.application",
                "delete.loan.application",
                "view.loan.history",
                "create.member.resign",
                "view.account.configuration",
                "create.account.configuration",
                "update.account.configuration",
                "delete.account.configuration",
                "view.master.qna",
                "create.master.qna",
                "update.master.qna",
                "delete.master.qna"],
        "DANSEK" => [
                "create.account.register",
                "create.account.login",
                "create.account.forgot_password",
                "view.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "view.dashboard.member_card",
                "view.dashboard.news",
                "view.deposit.main_deposit",
                "view.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "view.deposit.shu",
                "create.deposit_transaction.deposit_application",
                "create.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "update.loan.approval",
                "view.loan.detail",
                "update.loan.history",
                "view.member.resign",
                "create.member.resign",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "ADMIN_AREA" => [
                "view.transaction.management",
                "create.account.register",
                "create.account.login",
                "create.account.forgot_password",
                "create.account.bank_data",
                "view.dashboard.news",
                "view.deposit.main_deposit",
                "view.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "view.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "create.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "create.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "create.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "create.deposit_transaction.history",
                "view.loan.approval",
                "update.loan.approval",
                "view.loan.history",
                "view.member.total_member",
                "create.member.registration",
                "view.member.bank",
                "create.member.bank",
                "view.member.resign",
                "create.member.resign",
                "update.member.resign",
                "view.member.plafond",
                "view.member.loan",
                "update.member.loan",
                "view.transaction.member.retrieve.deposit",
                "update.transaction.member.retrieve.deposit",
                "view.transaction.member.change.deposit",
                "update.transaction.member.change.deposit",
                "view.member.resign",
                "update.member.resign",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "HO.AREA" => [
                "view.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.application",
                "update.loan.application",
                "view.loan.approval",
                "update.loan.approval",
                "view.loan.detail",
                "update.loan.detail",
                "view.loan.history",
                "update.loan.history",
                "view.member.bank",
                "view.member.resign",
                "create.member.resign",
                "update.member.resign",
                "view.loan.transaction",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "SUPERVISOR" => [
                "create.account.register",
                "create.account.login",
                "create.account.forgot_password",
                "create.account.bank_data",
                "view.dashboard.loan_total",
                "create.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "create.dashboard.deposit_total",
                "view.dashboard.member_card",
                "create.dashboard.member_card",
                "view.dashboard.news",
                "create.dashboard.news",
                "view.deposit.main_deposit",
                "update.deposit.main_deposit",
                "view.deposit.required_deposit",
                "update.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "update.deposit.voluntary_deposit",
                "view.deposit.shu",
                "update.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "create.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "create.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "create.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "create.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.application",
                "create.loan.application",
                "update.loan.application",
                "view.loan.approval",
                "create.loan.approval",
                "update.loan.approval",
                "view.loan.detail",
                "create.loan.detail",
                "update.loan.detail",
                "view.loan.history",
                "create.loan.history",
                "update.loan.history",
                "view.shu.config",
                "create.shu.config",
                "update.shu.config",
                "view.shu.history",
                "create.shu.history",
                "update.shu.history",
                "view.member.total_member",
                "view.member.configuration",
                "create.member.configuration",
                "update.member.configuration",
                "view.member.registration",
                "create.member.registration",
                "update.member.registration",
                "delete.member.registration",
                "view.member.work_configuration",
                "create.member.work_configuration",
                "update.member.work_configuration",
                "view.member.bank",
                "create.member.bank",
                "update.member.bank",
                "view.member.resign",
                "create.member.resign",
                "update.member.resign",
                "view.master.area",
                "create.master.area",
                "update.master.area",
                "delete.master.area",
                "view.master.location",
                "create.master.location",
                "update.master.location",
                "delete.master.location",
                "view.master.project",
                "create.master.project",
                "update.master.project",
                "delete.master.project",
                "view.master.position",
                "create.master.position",
                "update.master.position",
                "delete.master.position",
                "view.report.per_member",
                "create.report.per_member",
                "update.report.per_member",
                "view.report.per_area",
                "create.report.per_area",
                "update.report.per_area",
                "view.report.annual_loan",
                "view.report.annual_deposit",
                "view.report.annual_shu",
                "create.report.annual_shu",
                "update.report.annual_shu",
                "view.loan.transaction",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "PENGURUS_1" => [
                "view.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "view.dashboard.member_card",
                "view.dashboard.news",
                "view.deposit.main_deposit",
                "view.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "view.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.application",
                "update.loan.application",
                "view.loan.approval",
                "update.loan.approval",
                "view.shu.config",
                "update.shu.config",
                "view.shu.history",
                "update.shu.history",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "PENGURUS_2" => [
                "view.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "view.dashboard.member_card",
                "view.dashboard.news",
                "view.deposit.main_deposit",
                "view.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "view.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.application",
                "update.loan.application",
                "view.loan.approval",
                "update.loan.approval",
                "view.shu.config",
                "update.shu.config",
                "view.shu.history",
                "update.shu.history",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "PENGAWAS_1" => [
                "view.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "view.dashboard.member_card",
                "view.dashboard.news",
                "view.deposit.main_deposit",
                "view.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "view.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.application",
                "update.loan.application",
                "view.loan.approval",
                "update.loan.approval",
                "view.shu.config",
                "update.shu.config",
                "view.shu.history",
                "update.shu.history",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "PENGAWAS_2" => [
                "view.dashboard.loan_total",
                "view.dashboard.deposit_total",
                "view.dashboard.member_card",
                "view.dashboard.news",
                "view.deposit.main_deposit",
                "view.deposit.required_deposit",
                "view.deposit.voluntary_deposit",
                "view.deposit.shu",
                "view.deposit_transaction.deposit_application",
                "update.deposit_transaction.deposit_application",
                "view.deposit_transaction.cashing_application",
                "update.deposit_transaction.cashing_application",
                "view.deposit_transaction.cashing",
                "update.deposit_transaction.cashing",
                "view.deposit_transaction.history",
                "update.deposit_transaction.history",
                "view.loan.application",
                "update.loan.application",
                "view.loan.approval",
                "update.loan.approval",
                "view.shu.config",
                "update.shu.config",
                "view.shu.history",
                "update.shu.history",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "PENGAWAS_3" => [
            "create.account.register",
            "create.account.login",
            "create.account.forgot_password",
            "create.account.bank_data",
            "view.dashboard.loan_total",
            "create.dashboard.loan_total",
            "view.dashboard.deposit_total",
            "create.dashboard.deposit_total",
            "view.dashboard.member_card",
            "create.dashboard.member_card",
            "view.dashboard.news",
            "create.dashboard.news",
            "view.deposit.main_deposit",
            "update.deposit.main_deposit",
            "view.deposit.required_deposit",
            "update.deposit.required_deposit",
            "view.deposit.voluntary_deposit",
            "update.deposit.voluntary_deposit",
            "view.deposit.shu",
            "update.deposit.shu",
            "view.deposit_transaction.deposit_application",
            "create.deposit_transaction.deposit_application",
            "update.deposit_transaction.deposit_application",
            "view.deposit_transaction.cashing_application",
            "create.deposit_transaction.cashing_application",
            "update.deposit_transaction.cashing_application",
            "view.deposit_transaction.cashing",
            "create.deposit_transaction.cashing",
            "update.deposit_transaction.cashing",
            "view.deposit_transaction.history",
            "create.deposit_transaction.history",
            "update.deposit_transaction.history",
            "view.loan.application",
            "create.loan.application",
            "update.loan.application",
            "view.loan.approval",
            "create.loan.approval",
            "update.loan.approval",
            "view.loan.detail",
            "create.loan.detail",
            "update.loan.detail",
            "view.loan.history",
            "create.loan.history",
            "update.loan.history",
            "view.shu.config",
            "create.shu.config",
            "update.shu.config",
            "view.shu.history",
            "create.shu.history",
            "update.shu.history",
            "view.member.total_member",
            "view.member.configuration",
            "create.member.configuration",
            "update.member.configuration",
            "view.member.registration",
            "create.member.registration",
            "update.member.registration",
            "delete.member.registration",
            "view.member.work_configuration",
            "create.member.work_configuration",
            "update.member.work_configuration",
            "view.member.bank",
            "create.member.bank",
            "update.member.bank",
            "view.member.resign",
            "create.member.resign",
            "update.member.resign",
            "view.master.area",
            "create.master.area",
            "update.master.area",
            "delete.master.area",
            "view.master.location",
            "create.master.location",
            "update.master.location",
            "delete.master.location",
            "view.master.project",
            "create.master.project",
            "update.master.project",
            "delete.master.project",
            "view.master.position",
            "create.master.position",
            "update.master.position",
            "delete.master.position",
            "view.report.per_member",
            "create.report.per_member",
            "update.report.per_member",
            "view.report.per_area",
            "create.report.per_area",
            "update.report.per_area",
            "view.report.annual_loan",
            "view.report.annual_deposit",
            "view.report.annual_shu",
            "create.report.annual_shu",
            "update.report.annual_shu",
            "view.loan.transaction",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "SUPERVISOR" => [
            "view.dashboard.loan_total",
            "view.dashboard.deposit_total",
            "view.dashboard.member_card",
            "view.dashboard.news",
            "view.deposit.main_deposit",
            "view.deposit.required_deposit",
            "view.deposit.voluntary_deposit",
            "view.deposit.shu",
            "view.deposit_transaction.deposit_application",
            "update.deposit_transaction.deposit_application",
            "view.deposit_transaction.cashing_application",
            "update.deposit_transaction.cashing_application",
            "view.deposit_transaction.cashing",
            "update.deposit_transaction.cashing",
            "view.deposit_transaction.history",
            "update.deposit_transaction.history",
            "view.loan.application",
            "update.loan.application",
            "view.loan.approval",
            "update.loan.approval",
            "view.shu.config",
            "update.shu.config",
            "view.shu.history",
            "update.shu.history",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "GENERAL_MANAGER" => [
            "view.dashboard.loan_total",
            "view.dashboard.deposit_total",
            "view.dashboard.member_card",
            "view.dashboard.news",
            "view.deposit.main_deposit",
            "view.deposit.required_deposit",
            "view.deposit.voluntary_deposit",
            "view.deposit.shu",
            "view.deposit_transaction.deposit_application",
            "update.deposit_transaction.deposit_application",
            "view.deposit_transaction.cashing_application",
            "update.deposit_transaction.cashing_application",
            "view.deposit_transaction.cashing",
            "update.deposit_transaction.cashing",
            "view.deposit_transaction.history",
            "update.deposit_transaction.history",
            "view.loan.application",
            "update.loan.application",
            "view.loan.approval",
            "update.loan.approval",
            "view.shu.config",
            "update.shu.config",
            "view.shu.history",
            "update.shu.history",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "MANAGER" => [
            "view.dashboard.loan_total",
            "view.dashboard.deposit_total",
            "view.dashboard.member_card",
            "view.dashboard.news",
            "view.deposit.main_deposit",
            "view.deposit.required_deposit",
            "view.deposit.voluntary_deposit",
            "view.deposit.shu",
            "view.deposit_transaction.deposit_application",
            "update.deposit_transaction.deposit_application",
            "view.deposit_transaction.cashing_application",
            "update.deposit_transaction.cashing_application",
            "view.deposit_transaction.cashing",
            "update.deposit_transaction.cashing",
            "view.deposit_transaction.history",
            "update.deposit_transaction.history",
            "view.loan.application",
            "update.loan.application",
            "view.loan.approval",
            "update.loan.approval",
            "view.shu.config",
            "update.shu.config",
            "view.shu.history",
            "update.shu.history",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "DIREKTUR_UTAMA" => [
            "view.transaction.management",
            "view.account.register",
            "view.account.login",
            "view.account.forgot_password",
            "view.account.bank_data",
            "view.dashboard.loan_total",
            "create.dashboard.loan_total",
            "view.dashboard.deposit_total",
            "create.dashboard.deposit_total",
            "view.dashboard.member_card",
            "create.dashboard.member_card",
            "view.dashboard.news",
            "create.dashboard.news",
            "view.deposit.main_deposit",
            "update.deposit.main_deposit",
            "view.deposit.required_deposit",
            "update.deposit.required_deposit",
            "view.deposit.voluntary_deposit",
            "update.deposit.voluntary_deposit",
            "view.deposit.shu",
            "update.deposit.shu",
            "view.deposit_transaction.deposit_application",
            "create.deposit_transaction.deposit_application",
            "update.deposit_transaction.deposit_application",
            "view.deposit_transaction.cashing_application",
            "create.deposit_transaction.cashing_application",
            "update.deposit_transaction.cashing_application",
            "view.deposit_transaction.cashing",
            "create.deposit_transaction.cashing",
            "update.deposit_transaction.cashing",
            "view.deposit_transaction.history",
            "create.deposit_transaction.history",
            "update.deposit_transaction.history",
            "view.loan.application",
            "create.loan.application",
            "update.loan.application",
            "view.loan.approval",
            "create.loan.approval",
            "update.loan.approval",
            "view.loan.detail",
            "create.loan.detail",
            "update.loan.detail",
            "view.loan.history",
            "create.loan.history",
            "update.loan.history",
            "view.shu.config",
            "create.shu.config",
            "update.shu.config",
            "delete.shu.config",
            "view.shu.history",
            "create.shu.history",
            "update.shu.history",
            "delete.shu.history",
            "view.member.total_member",
            "view.member.configuration",
            "create.member.configuration",
            "update.member.configuration",
            "view.member.registration",
            "create.member.registration",
            "update.member.registration",
            "delete.member.registration",
            "view.member.bank",
            "create.member.bank",
            "update.member.bank",
            "view.member.resign",
            "create.member.resign",
            "update.member.resign",
            "view.master.area",
            "create.master.area",
            "update.master.area",
            "delete.master.area",
            "view.master.transaction-type",
            "create.master.transaction-type",
            "update.master.transaction-type",
            "delete.master.transaction-type",
            "view.master.location",
            "create.master.location",
            "update.master.location",
            "delete.master.location",
            "view.master.project",
            "create.master.project",
            "update.master.project",
            "delete.master.project",
            "view.master.position",
            "create.master.position",
            "update.master.position",
            "delete.master.position",
            "view.report.per_member",
            "view.report.per_area",
            "view.report.annual_shu",
            "create.report.annual_shu",
            "update.report.annual_shu",
            "delete.report.annual_shu",
            "view.loan.transaction",
            "view.auth.management",
            "view.auth.user",
            "create.auth.user",
            "update.auth.user",
            "delete.auth.user",
            "view.project.management",
            "view.master.branch",
            "create.master.branch",
            "update.master.branch",
            "delete.master.branch",
            "view.master.policy",
            "create.master.policy",
            "update.master.policy",
            "delete.master.policy",
            "view.member.plafond",
            "create.member.plafond",
            "update.member.plafond",
            "delete.member.plafond",
            "view.auth.level",
            "create.auth.level",
            "update.auth.level",
            "delete.auth.level",
            "view.master.deposit",
            "create.master.deposit",
            "update.master.deposit",
            "delete.master.deposit",
            "view.master.loan",
            "create.master.loan",
            "update.master.loan",
            "delete.master.loan",
            "view.transaction.member.plafond",
            "create.transaction.member.plafond",
            "update.transaction.member.plafond",
            "delete.transaction.member.plafond",
            "view.transaction.member.loan",
            "create.transaction.member.loan",
            "update.transaction.member.loan",
            "delete.transaction.member.loan",
            "view.transaction.member.deposit",
            "create.transaction.member.deposit",
            "update.transaction.member.deposit",
            "delete.transaction.member.deposit",
            "view.transaction.member.retrieve.deposit",
            "create.transaction.member.retrieve.deposit",
            "update.transaction.member.retrieve.deposit",
            "delete.transaction.member.retrieve.deposit",
            "view.transaction.member.change.deposit",
            "create.transaction.member.change.deposit",
            "update.transaction.member.change.deposit",
            "delete.transaction.member.change.deposit",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
            "create.master.qna",
            "update.master.qna",
            "delete.master.qna"],
        "DIREKTUR" => [
            "view.transaction.management",
            "view.account.register",
            "view.account.login",
            "view.account.forgot_password",
            "view.account.bank_data",
            "view.dashboard.loan_total",
            "create.dashboard.loan_total",
            "view.dashboard.deposit_total",
            "create.dashboard.deposit_total",
            "view.dashboard.member_card",
            "create.dashboard.member_card",
            "view.dashboard.news",
            "create.dashboard.news",
            "view.deposit.main_deposit",
            "update.deposit.main_deposit",
            "view.deposit.required_deposit",
            "update.deposit.required_deposit",
            "view.deposit.voluntary_deposit",
            "update.deposit.voluntary_deposit",
            "view.deposit.shu",
            "update.deposit.shu",
            "view.deposit_transaction.deposit_application",
            "create.deposit_transaction.deposit_application",
            "update.deposit_transaction.deposit_application",
            "view.deposit_transaction.cashing_application",
            "create.deposit_transaction.cashing_application",
            "update.deposit_transaction.cashing_application",
            "view.deposit_transaction.cashing",
            "create.deposit_transaction.cashing",
            "update.deposit_transaction.cashing",
            "view.deposit_transaction.history",
            "create.deposit_transaction.history",
            "update.deposit_transaction.history",
            "view.loan.application",
            "create.loan.application",
            "update.loan.application",
            "view.loan.approval",
            "create.loan.approval",
            "update.loan.approval",
            "view.loan.detail",
            "create.loan.detail",
            "update.loan.detail",
            "view.loan.history",
            "create.loan.history",
            "update.loan.history",
            "view.shu.config",
            "create.shu.config",
            "update.shu.config",
            "delete.shu.config",
            "view.shu.history",
            "create.shu.history",
            "update.shu.history",
            "delete.shu.history",
            "view.member.total_member",
            "view.member.configuration",
            "create.member.configuration",
            "update.member.configuration",
            "view.member.registration",
            "create.member.registration",
            "update.member.registration",
            "delete.member.registration",
            "view.member.bank",
            "create.member.bank",
            "update.member.bank",
            "view.member.resign",
            "create.member.resign",
            "update.member.resign",
            "view.master.area",
            "create.master.area",
            "update.master.area",
            "delete.master.area",
            "view.master.transaction-type",
            "create.master.transaction-type",
            "update.master.transaction-type",
            "delete.master.transaction-type",
            "view.master.location",
            "create.master.location",
            "update.master.location",
            "delete.master.location",
            "view.master.project",
            "create.master.project",
            "update.master.project",
            "delete.master.project",
            "view.master.position",
            "create.master.position",
            "update.master.position",
            "delete.master.position",
            "view.report.per_member",
            "view.report.per_area",
            "view.report.annual_shu",
            "create.report.annual_shu",
            "update.report.annual_shu",
            "delete.report.annual_shu",
            "view.loan.transaction",
            "view.auth.management",
            "view.auth.user",
            "create.auth.user",
            "update.auth.user",
            "delete.auth.user",
            "view.project.management",
            "view.master.branch",
            "create.master.branch",
            "update.master.branch",
            "delete.master.branch",
            "view.master.policy",
            "create.master.policy",
            "update.master.policy",
            "delete.master.policy",
            "view.member.plafond",
            "create.member.plafond",
            "update.member.plafond",
            "delete.member.plafond",
            "view.auth.level",
            "create.auth.level",
            "update.auth.level",
            "delete.auth.level",
            "view.master.deposit",
            "create.master.deposit",
            "update.master.deposit",
            "delete.master.deposit",
            "view.master.loan",
            "create.master.loan",
            "update.master.loan",
            "delete.master.loan",
            "view.transaction.member.plafond",
            "create.transaction.member.plafond",
            "update.transaction.member.plafond",
            "delete.transaction.member.plafond",
            "view.transaction.member.loan",
            "create.transaction.member.loan",
            "update.transaction.member.loan",
            "delete.transaction.member.loan",
            "view.transaction.member.deposit",
            "create.transaction.member.deposit",
            "update.transaction.member.deposit",
            "delete.transaction.member.deposit",
            "view.transaction.member.retrieve.deposit",
            "create.transaction.member.retrieve.deposit",
            "update.transaction.member.retrieve.deposit",
            "delete.transaction.member.retrieve.deposit",
            "view.transaction.member.change.deposit",
            "create.transaction.member.change.deposit",
            "update.transaction.member.change.deposit",
            "delete.transaction.member.change.deposit",
            "view.account.configuration",
            "create.account.configuration",
            "update.account.configuration",
            "delete.account.configuration",
            "view.master.qna",
                "create.master.qna",
                "update.master.qna",
                "delete.master.qna"]
        ]
];
